---
apiVersion: v1
kind: Pod
metadata:
    name: myapp-nginx
    labels:
             name: test
             version: v1
spec:
    containers:
        - image: nginx
          name: mynignx
          ports:
            - containerPort: 80
              protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
    name: myapp-httpd
    labels:
             name: test
             version: v2
spec:
    containers:
        - image: httpd
          name: mynignx
          ports:
            - containerPort: 80
              protocol: TCP

