apiVersion: v1
kind: ReplicationController
metadata:
      name: my-rc
spec: 
    replicas: 4
    selector: 
        name: test 
    template:
      metadata: 
          name: myapp-nginx
          labels:
              name: test
      spec:
          containers:
              - image: nginx
                name: mynignx
                ports:
                  - containerPort: 80
                    protocol: TCP
         

